FirstMVCSQ016/Controllers/WeatherForcastController.cs
using FirstMVCSQ016.Models;
using FirstMVCSQ016.Services;
using FirstMVCSQ016.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCSQ016.Controllers
{
    public class WeatherForcastController : Controller
    {
        private readonly IWeatherForecastService _weatherForecastService;
        public WeatherForcastController(IWeatherForecastService weatherForecastService)
        {
            _weatherForecastService = weatherForecastService;
        }

        [Authorize(Roles = "admin, editor")]  // you must be logged in, you musst be an editor or an admin
        [Authorize(Policy = "CanAdd")]
        public async Task<IActionResult> AddWeatherForcast(AddNewWeatherForcastViewModel model)
        {
            if(ModelState.IsValid)
            {
                var result = await _weatherForecastService.AddNewAsync(model);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

FirstMVCSQ016/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> _signInManager;
@inject UserManager<AppUser> _userManager;
@{
    var user = _userManager.GetUserAsync(User).Result;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCSQ016</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVCSQ016.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstMVCSQ016</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UploadImage">Upload-Image</a>
                        </li>
                        <li class="nav-item">
                            @if (_signInManager.IsSignedIn(User))
                            {
                                @if (_userManager.IsInRoleAsync(user, "admin").Result || _userManager.IsInRoleAsync(user, "editor").Result)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="WeatherForcast" asp-action="AddWeatherForcast">Add New</a>
                                }
                            }
                        </li>

                        <li class="nav-item">
                            @if (_signInManager.IsSignedIn(User))
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            }else{
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            }
                        </li>
                    </ul>
                </div>
                @if (_signInManager.IsSignedIn(User))
                {
                    <div class="thumbnail-loggedin-user">
                        <div class="thumb-image">
                            <img />
                        </div>
                        <div>
                            <div class="user-name">@_userManager.GetUserAsync(User).Result.FirstName</div>
                            <span class="login-status">Online</span>
                        </div>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FirstMVCSQ016 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>